<?php
/** @var \Pankaj\Testimonial\Block\Template $block */
/** @var \Pankaj\Testimonial\ViewModel\TestimonialView $viewModel */
$viewModel = $block->getViewModel();
?>

<div class="testimonial">
    <h1><?=$block->getName()?></h1>

<?php foreach ($block->getTestimonialCollection() as $testimonial) : ?>  
<div class="container">
    <img src="<?= $viewModel->getImageUrl($testimonial->getImage()) ?>" alt="<?= $testimonial->getImage() ?>" width="90" >
    <!-- <img src="<?php //echo $block->getViewFileUrl('Pankaj_Testimonial::images/default_user.png') ?>" alt="Default User Image" width="90"> -->

    <p><span> <?= $block->getCustomerName($testimonial->getCustomerId())?>.</span> <?= $testimonial->getDesignation() ?>.</p>
    <p><?= $testimonial->getTitle() ?></p>
    <?= $testimonial->getContent() ?>
</div>
<?php endforeach; ?>
    
</div>

<?= ($block->getChildHtml('pager'))??$block->getChildHtml('pager'); ?>
